### ISSUE TITLE
h64 result big endian?

### ISSUE THREAD

**Issue by mischnic** [jungomi/xxhash-wasm#20]
I would have expected these three calls to all yield the same result:

```js
import xxhash from "xxhash-wasm";

const { h64, h64Raw } = await xxhash();

function toHex(buffer) {
	return Array.from(buffer, (x) =>
		String(x.toString(16)).padStart(2, "0")
	).join("");
}

console.log(h64("abc")); // 44bc2cf5ad770999
console.log(toHex(h64Raw((new TextEncoder()).encode("abc")))); // f52cbc44990977ad
console.log(toHex(h64Raw(new Uint8Array([97, 98, 99])))); // f52cbc44990977ad
```

However, the bytes in the two halfs of the result are mirrored in `h64` compared to `h64Raw`. This is because the `true` paremeter here uses big endian (which is not how for example `Buffer.from(...).toString(16)` on Node behaves when converting a buffer into a hex string). Is this intentional?

https://github.com/jungomi/xxhash-wasm/blob/912cd6f897c095c144f9ba68d986e593de829d09/src/index.js#L65-L66

**Comment by jungomi** [comment]
I think there is a misunderstanding between the literal value and the memory representation (endianness).

## Endianness

Endianness can be quite tricky in many places, because most of the time it is done automatically and you never notice it, but when you start using *"manual memory"* on top of a system that handles it already, you need to be careful not to mix them, especially since the representation does not reflect the underlying memory.

Let's first take a look at the memory representation for the string `abcd`, where each character is represented by one byte (given in hexadecimal: `a = 0x61`, `b = 0x62`, `c = 0x63`, `d = 0x64`):

Little-Endian
```
64 63 62 61
```

Big-Endian
```
61 62 63 64
```

With strings where each character is exactly one byte, that seems quite intuitive, as on one side you have the literal value (string) and on the other you have the memory representation (hexadecimal). It becomes much more confusing when your literal value is also given in hexadecimal.

*If I give you the literal value `0x61626364` (e.g. `const value = 0x61626364`), does it matter what endianness your system uses?* **No**, just like a string or a decimal that value is completely independent of the memory representation.

*How is it represented in memory?* Exactly like the `abcd` example, as it happens to be the corresponding hexadecimal representation. And this is why it can get very confusing.

*Does that mean hexadecimal literals are big-endian?* Strictly speaking, No, there is no such a thing as endianness, because there are no bytes, it's just a number, where the largest digit is on the left and the smallest on the right, just like decimal numbers. In that regard, you might argue it could be considered big-endian, as that stores the number in memory following the same idea.

## Output of `h64Raw`

The 32-bit words that are stored in the buffer are little-endian and the `true` argument is in fact setting it to treat it as little-endian, as opposed to the default being big-endian, as mentioned in the MDN documentation of [`DataView.prototype.getUint32()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getUint32):

> ## Syntax
> ```javascript
> getUint32(byteOffset)
> getUint32(byteOffset, littleEndian)
> ```
> ### Parameters
> `byteOffset`
> The offset, in byte, from the start of the view where to read the data.
>
> `littleEndian`
> *Optional* Indicates whether the 32-bit int is stored in little- or big-endian format. If false or undefined, a big-endian value is read.

That means if you loop over the bytes, as you do, you are treating it as big-endian, but as it is little-endian, the bytes within a 32-bit word are reversed.

Admittedly, the endianness hasn't been considered in full detail at the time, hence the word order doesn't follow the endianness and it might even be incorrect on big-endian systems, but since almost all current processors are little-endian, it is an extremely unlikely scenario. Ideally, the endianness should be handled properly.

## Correctness of `h64`

The output of `h64` has been verified with the tests with the expected values taken from other implementations:

https://github.com/jungomi/xxhash-wasm/blob/c1939fb66d4fe54c493ed561033d3cc9ec4a5b31/test/index.test.js#L7-L28

Similarly, `h64Raw` is also passing the same test cases, meaning that the output you get from `h64Raw` is verifiably a `Uint8Array` with two 32-bit words that are stored in little-endian, i.e. byte order of the whole array is `[3, 2, 1, 0, 7, 6, 5, 4]`. This is not really a standardised output format, because it was basically a workaround to get 64-bit integers working in JavaScript before `BigInt` had been introduced and was an implementation detail, which was later added to the public API, because someone wanted to avoid the string creations, hence it was just exposed and was not redesigned to be standardised or compatible with anything else.

**Comment by mischnic** [comment]
I see, thank you for the details answer!

> byte order of the whole array is [3, 2, 1, 0, 7, 6, 5, 4]

My mistake was that I though the byte order was `7, 6, ...., 1, 0`, so that's why my `toHex` didn't match the result of `h64()`.
